language: node_js
node_js:
  - 10

before_script:
  - npm pack
  - npm i -g $(find . -name 'nprr-*.tgz') # install the package globally

jobs:
  include:
    - stage: Project build
      node_js: node
      # the next are truly E2E tests
      script: nprr test
      script: nprr unit:test -t 'Trap succeed'
      script: nprr unit:test -- -t 'Trap succeed'
    - stage: Produce Coverage
      node_js: node
      script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
    - stage: Stryker
      node_js: node
      script: npm run stryker

after_success: npm run semantic-release
